### ISSUE TITLE
connection.js in config

### ISSUE THREAD

**Issue by Joyce77777777** [topcowmoo/unbreakable-cream#17]
Set up database connection

**Comment by sbanati** [comment]
great job! just a side note , lets make sure the .env file has the correct environment variables mainly the port.

**Comment by sbanati** [comment]
Sorry I took a little bit of time to approve your request, ill just put some screen shots of your code here for records. Great job 


![Image](https://github.com/topcowmoo/unbreakable-cream/assets/149754544/bf04dd2b-5e9b-4d2c-84f7-8f697d12b056)



![Image](https://github.com/topcowmoo/unbreakable-cream/assets/149754544/9c042a79-28b5-4015-b312-cbfde92c72c6)
