### ISSUE TITLE
Create a Like model (Like.js)

### ISSUE THREAD

**Issue by blockdoyle** [topcowmoo/unbreakable-cream#26]
Define a Sequelize model for a Like object. Set the  attributes and options

# User Story:
- WHEN the user likes a post
- THEN a like is added to a post
- A **USER** may have **MANY** likes.

**Comment by sbanati** [comment]
great work 

![Image](https://github.com/topcowmoo/unbreakable-cream/assets/149754544/c94a0ec3-84aa-48ef-80fd-8a2c5dba0554)
