### ISSUE TITLE
Create a Favorites model (Favorites.js)

### ISSUE THREAD

**Issue by blockdoyle** [topcowmoo/unbreakable-cream#27]
Define a Sequelize model for a Favorite object. Set the  attributes and options

# User Story:
- WHEN the user likes a post
- THEN a like is added to a post
- A **USER** may have **MANY** likes.

**Comment by sbanati** [comment]
great work  
![Image](https://github.com/topcowmoo/unbreakable-cream/assets/149754544/28fbe5af-9c16-4749-b21e-154fd95013a0)
