### ISSUE TITLE
main.handlebars

### ISSUE THREAD

**Issue by AishaJoy** [topcowmoo/unbreakable-cream#31]

**Comment by AishaJoy** [comment]
Creating static HTML elements and connecting to CSS file for general styling

**Comment by sbanati** [comment]
First take on main.handlebar , this may be changed as we continue development 

![Image](https://github.com/topcowmoo/unbreakable-cream/assets/149754544/e7fd48b6-261b-4520-8302-74ca2b18c15b)



![Image](https://github.com/topcowmoo/unbreakable-cream/assets/149754544/3615feab-33aa-458f-a7f9-5224190ea101)
