### ISSUE TITLE
Create example seeds for User, Post, and Comment

### ISSUE THREAD

**Issue by blockdoyle** [topcowmoo/unbreakable-cream#35]
Creating some example seeds for User, Post, and Comment.

**Comment by sbanati** [comment]
Great stuff 

![Image](https://github.com/topcowmoo/unbreakable-cream/assets/149754544/31b1f8e5-a43e-4ef8-abb7-8f071fe06e24)



![Image](https://github.com/topcowmoo/unbreakable-cream/assets/149754544/ad4ba27f-f077-4162-b67f-649103545682)



![Image](https://github.com/topcowmoo/unbreakable-cream/assets/149754544/f14b680c-2be6-4632-af43-da5b23163154)
