### ISSUE TITLE
Apply prettier to Post, Comment, User. Also fix the filename for Post.js

### ISSUE THREAD

**Issue by blockdoyle** [topcowmoo/unbreakable-cream#43]
Applied prettier to respective files, and fixed the capitalization in Post.js

**Comment by sbanati** [comment]
These are the initial prettier changes , nicely done 

![Image](https://github.com/topcowmoo/unbreakable-cream/assets/149754544/aaa53f18-d14a-4a74-8ad7-68fd021154f4)
