### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by topcowmoo** [topcowmoo/unbreakable-cream#62]
Create README.md

**Comment by topcowmoo** [comment]
I've created the README.md. 

The commented areas are still outstanding. Please let me know your thoughts or send me a draft of what you want included in those sections. Thanks!!

**OUTSTANDING ITEMS:**

**Project Description**

![Image](https://github.com/topcowmoo/unbreakable-cream/assets/149528212/2c470b15-6a26-4717-ae12-7eb8bbb179af)

**About the Project and Screenshots**

![Image](https://github.com/topcowmoo/unbreakable-cream/assets/149528212/f7229372-f76e-4de3-882c-1ff54d5768df)

**Contact Section - email address for Sahil, Saran and Brock
Acknowledgments - Whole section**

![Image](https://github.com/topcowmoo/unbreakable-cream/assets/149528212/0ec71c4a-ba96-48d6-a17a-db8405f934db)

**Comment by sbanati** [comment]
hey salvatore, can you remove the image pngs and turn them into markdown badges instead.

**Comment by sbanati** [comment]
in the readme you used the .gif extension image  for thje logo. It is showing a play button but the animation is not working. Can you fix this to just be a static image with png extension please

**Comment by sbanati** [comment]
my email is also smbanati@gmail.com , i think its a typo in the readme section

**Comment by sbanati** [comment]
In acknowledgements can you also add the link you used for the icons, also add the Xpert Learning Assistant or ChatGPT whichever, also add font-awesome for icons and if you used anything to make the logo
